class formats:
    green = '\033[92m'
    red = '\033[91m'
    yellow = '\033[93m'
    blue = '\033[34m'
    ends = '\033[0m'

## Prueb Data
dict = [
    {'id': 94, 'name': 'David Fernandez'},
    {'id': 62, 'name': 'Julia Gomez'},
    {'id': 5, 'name': 'Carlos Sanchez'},
    {'id': 53, 'name': 'Sofia Martinez'},
    {'id': 8, 'name': 'Isabel Gutierrez'},
    {'id': 18, 'name': 'Ana Torres'},
    {'id': 12, 'name': 'Luis Fernandez'},
    {'id': 45, 'name': 'Pedro Ordaz'},
    {'id': 78, 'name': 'Raul Ramirez'},
    {'id': 33, 'name': 'Maria Lopez'},
    {'id': 71, 'name': 'Juan Perez'},
    {'id': 80, 'name': 'Angel Mariscurrena'},
    {'id': 15, 'name': 'Eva Ruiz'},
    {'id': 38, 'name': 'Alfredo Jimenez'},
    {'id': 40, 'name': 'Marta Delgado'},
    {'id': 4, 'name': 'Fernando Alvarez'},
    {'id': 21, 'name': 'Laura Torres'},
    {'id': 23, 'name': 'Gabriel Martinez'},
    {'id': 16, 'name': 'Antonio Castro'},
    {'id': 36, 'name': 'Ricardo Garcia'},
    {'id': 10, 'name': 'Alba Rodriguez'},
    {'id': 3, 'name': 'Cristina Gonzalez'},
    {'id': 60, 'name': 'Roberto Perez'},
    {'id': 42, 'name': 'Sandra Herrera'},
    {'id': 19, 'name': 'Carmen Ruiz'},
    {'id': 48, 'name': 'Diego Fernandez'},
    {'id': 30, 'name': 'Jose Luis Martin'},
    {'id': 29, 'name': 'Daniel Paredes'},
    {'id': 73, 'name': 'Hector Vargas'},
    {'id': 35, 'name': 'Lorena Romero'},
    {'id': 63, 'name': 'Raquel Gonzalez'},
    {'id': 64, 'name': 'Nadia Ramos'},
    {'id': 41, 'name': 'Vicente Perez'},
    {'id': 49, 'name': 'Esteban Alvarez'},
    {'id': 56, 'name': 'Rosa Garcia'},
    {'id': 70, 'name': 'Lydia Navarro'},
    {'id': 59, 'name': 'Javier Soler'},
    {'id': 24, 'name': 'Natalia Martin'},
    {'id': 55, 'name': 'Francisco Mendez'},
    {'id': 50, 'name': 'Ana Beatriz Ruiz'},
    {'id': 61, 'name': 'Beatriz Ruiz'},
    {'id': 77, 'name': 'Carmen Lopez'},
    {'id': 25, 'name': 'Victor Sanchez'},
    {'id': 2, 'name': 'Elena Diaz'},
    {'id': 72, 'name': 'Samuel Gutierrez'},
    {'id': 9, 'name': 'Vanessa Perez'},
    {'id': 76, 'name': 'Esteban Rodriguez'},
    {'id': 66, 'name': 'Sergio Lopez'},
    {'id': 37, 'name': 'Paula Lopez'},
    {'id': 44, 'name': 'Oscar Garcia'},
    {'id': 69, 'name': 'Nuria Torres'},
    {'id': 58, 'name': 'Pablo Hernandez'},
    {'id': 17, 'name': 'Gonzalo Rivera'},
    {'id': 11, 'name': 'Mario Gonzalez'},
    {'id': 75, 'name': 'Juan Carlos Martin'},
    {'id': 27, 'name': 'Manuel Perez'},
    {'id': 31, 'name': 'Patricia Ruiz'},
    {'id': 28, 'name': 'Eva Garcia'},
    {'id': 1, 'name': 'Juan Ortega'},
    {'id': 43, 'name': 'Sonia Gomez'},
    {'id': 68, 'name': 'Carlos Ruiz'},
    {'id': 34, 'name': 'Cristian Torres'},
    {'id': 67, 'name': 'Miguel Lopez'},
    {'id': 74, 'name': 'Adrian Gomez'},
    {'id': 65, 'name': 'Eva Lopez'},
    {'id': 32, 'name': 'Raul Perez'},
    {'id': 39, 'name': 'Oscar Ramos'},
    {'id': 20, 'name': 'Adela Ruiz'},
    {'id': 51, 'name': 'Santiago Paredes'},
    {'id': 52, 'name': 'Miguel Vargas'},
    {'id': 57, 'name': 'Clara Garcia'},
    {'id': 22, 'name': 'Adriana Moreno'},
    {'id': 79, 'name': 'Lucas Sanchez'},
    {'id': 13, 'name': 'Dolores Cruz'},
    {'id': 26, 'name': 'Raquel Lopez'},
    {'id': 14, 'name': 'Luis Martin'},
    {'id': 82, 'name': 'Valeria Ruiz'},
    {'id': 83, 'name': 'Adriana Garcia'},
    {'id': 84, 'name': 'Jaime Soler'},
    {'id': 85, 'name': 'Felipe Sanchez'},
    {'id': 86, 'name': 'Cecilia Delgado'},
    {'id': 87, 'name': 'Rafael Ortiz'},
    {'id': 88, 'name': 'Angela Navarro'},
    {'id': 89, 'name': 'Juan Pablo Perez'},
    {'id': 90, 'name': 'Cristina Ramos'},
    {'id': 91, 'name': 'Fernando Lopez'},
    {'id': 92, 'name': 'Oscar Torres'},
    {'id': 93, 'name': 'Javier Ruiz'},
    {'id': 95, 'name': 'Marta Fernandez'},
    {'id': 96, 'name': 'Ricardo Lopez'},
    {'id': 97, 'name': 'Laura Martin'},
    {'id': 98, 'name': 'Sandra Paredes'},
    {'id': 99, 'name': 'Luis Soler'},
    {'id': 100, 'name': 'Carlos Ramos'},
    {'id': 101, 'name': 'Carlos Juarez'},
    {'id': 102, 'name': 'Carlos Hernandez'},
    {'id': 103, 'name': 'Carlos Perez'},
    {'id': 104, 'name': 'Carlos Peralta'},
    {'id': 105, 'name': 'Carlos Benitez'},
    {'id': 106, 'name': 'Carlos Colosio'},
]